In [2]:
# 데이터선택 - row

In [4]:
import pandas as pd
df = pd.read_excel('file/score.xlsx',index_col='지원번호')

In [7]:
# loc-이름검색,iloc-index주소로 검색
# df.loc['1번']
# df.iloc[0]
df.index   # index 모두 출력
df.columns # columns 모두 출력

Index(['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기'], dtype='str')

In [8]:
# 컬럼 슬라이싱은 columns을 활용
# df['학교':'영어']  # col이름으로 슬라이싱 안됨.
# df[df.columns[1:5]] # columns 슬라이싱가능

# row출력
df.loc['3번']         # 1개출력
df.loc[['1번','2번']] # 2개출력
df.loc['3번','국어']  # 1개row에서 국어컬럼만 출력
df.loc['1번':'4번']   # 1번~4번까지 출력
df.loc['1번':'4번',['학교','영어']] # index슬라이싱, column슬라이싱

       학교  영어
지원번호
1번    신림고  85
2번    신림고  35
3번    신림고  75
4번    신림고  60

In [ ]:
# 컬럼 슬라이싱은 columns을 활용
# df['학교':'영어']  # col이름으로 슬라이싱 안됨.
# df[df.columns[1:5]] # columns 슬라이싱가능

# loc 형태 - row출력
df.loc['3번']         # 1개출력
df.loc[['1번','2번']] # 2개출력
df.loc['3번','국어']  # 1개row에서 국어컬럼만 출력
df.loc['1번':'4번']   # 1번~4번까지 출력
df.loc['1번':'4번','학교':'영어'] # index슬라이싱, column슬라이싱
df.loc['1번':'4번',['학교','영어']] # index슬라이싱, column2개는 리스트
df.loc[['1번','4번'],['학교','영어']] # index2개는리스트, column슬라이싱

       학교  영어
지원번호
1번    신림고  85
4번    신림고  60

In [ ]:
# iloc 형태 - row출력
df.loc['1번']
df.loc['1번':'4번']
df.iloc[0]
df.iloc[[0,2,4]]   # 2개는 리스트
df.iloc[0:4]       # iloc슬라이싱 가능
df.iloc[0:3,1:5]   # index슬라이싱,columns슬라이싱
df.iloc[[0,2],1:5] # index 2개는 리스트
df.iloc[[0,2],[1,3,5]] # index 2개는 리스트, columns 2개는 리스트

       학교  국어   수학
지원번호
1번    신림고  90  100
3번    신림고  80   70

In [54]:
df = pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3,usecols='B:D,J:O',index_col='행정기관')
df
df.iloc[[0,2,5],[0,1,2,4,5]]

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

              총 인구수     연령구간인구수     50~59세     70~79세     80~89세
행정기관
전국       51,159,889  51,159,889  8,684,663  4,381,844  2,144,715
부산광역시     3,251,625   3,251,625    533,582    352,270    152,648
광주광역시     1,398,538   1,398,538    242,861    107,235     51,212

In [ ]:
df = pd.read_excel('file/합계출산율_2026.xlsx',skiprows=28,nrows=2)
df.set_index('Unnamed: 0',inplace=True)
df.index.name='제목'
df.iloc[:,[0,3,4,6]]

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

           2016     2019     2020     2022
제목
출생아 수   406.200  302.700  272.300  249.200
합계 출산율    1.172    0.918    0.837    0.778

In [ ]:
df = df.T #축변경
df.iloc[[0,3,4,6]]

제목    출생아 수  합계 출산율
2016  406.2   1.172
2019  302.7   0.918
2020  272.3   0.837
2022  249.2   0.778