In [ ]:
import pandas as pd
# df=pd.read_excel('file/score_2.xlsx',index_col='지원번호')
# df

ValueError: Index 지원번호 invalid (sheet: 0)

In [9]:
df = pd.read_excel('file/j2025.xlsx',skiprows=2,index_col='행정기관')
df.sort_index()

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,행정기관코드,총인구수,세대수,세대당 인구,남자 인구수,여자 인구수,남여 비율
행정기관,,,,,,,
강원특별자치도,5100000000,"1,506,662","775,882",1.94,"757,981","748,681",1.01
경기도,4100000000,"13,773,918","6,189,087",2.23,"6,914,277","6,859,641",1.01
경상남도,4800000000,"3,191,645","1,558,906",2.05,"1,609,943","1,581,702",1.02
경상북도,4700000000,"2,492,677","1,303,782",1.91,"1,262,786","1,229,891",1.03
대구광역시,2700000000,"2,346,277","1,123,265",2.09,"1,148,130","1,198,147",0.96
대전광역시,3000000000,"1,442,838","706,437",2.04,"718,413","724,425",0.99
부산광역시,2600000000,"3,229,467","1,583,256",2.04,"1,568,318","1,661,149",0.94
서울특별시,1100000000,"9,281,625","4,525,061",2.05,"4,466,290","4,815,335",0.93
세종특별자치시,3600000000,"390,738","165,930",2.35,"194,589","196,149",0.99
울산광역시,3100000000,"1,086,373","502,387",2.16,"560,121","526,252",1.06
인천광역시,2800000000,"3,066,185","1,418,345",2.16,"1,530,650","1,535,535",1.00
전국,1000000000,"51,084,159","24,505,258",2.08,"25,412,088","25,672,071",0.99
전남광주통합특별시,1200000000,"3,155,803","1,579,291",2.00,"1,578,180","1,577,623",1.00
전북특별자치도,5200000000,"1,716,965","874,337",1.96,"855,796","861,169",0.99
제주특별자치도,5000000000,"662,681","317,767",2.09,"331,063","331,618",1.00
충청남도,4400000000,"2,138,938","1,072,860",1.99,"1,098,834","1,040,104",1.06
충청북도,4300000000,"1,601,367","808,665",1.98,"816,717","784,650",1.04

In [ ]:
#DataFrame 합치기 : concat , usecols : 컬럼선택해서 가져오기
# skiprows : 상단부분 제외후 가져오기
df1 =pd.read_csv('file/2014년졸음운전교통사고.csv',encoding='euc-kr')
df2 =pd.read_csv('file/2015년졸음운전교통사고.csv',encoding='euc-kr')
df3 =pd.read_csv('file/2016년졸음운전교통사고.csv',encoding='euc-kr')
# df = pd.concat([df1,df2,df3]) # DataFrame 합치기
# df.set_index('구분',inplace=True)
# df

          사고(건)  사망(명)  부상(명)
구분
2014년1월     169      7    347
2014년2월     145      3    268
2014년3월     206     12    358
2014년4월     182      4    360
2014년5월     218     17    474
2014년6월     233     13    457
2014년7월     229     14    431
2014년8월     222      9    447
2014년9월     225     15    430
2014년10월    210     14    392
2014년11월    209     10    386
2014년12월    178     12    329
2015년1월     205      8    375
2015년2월     175      8    375
2015년3월     237      4    492
2015년4월     227     10    486
2015년5월     231      9    504
2015년6월     207      8    401
2015년7월     273      7    556
2015년8월     268     19    534
2015년9월     252     10    501
2015년10월    214     14    475
2015년11월    199      3    398
2015년12월    213      8    428
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
import pandas as pd
df = pd.read_excel('file/j2025.xlsx',skiprows=2,usecols='B,D,I:N')
df.set_index()
df

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,행정기관,세대수,총인구수.1,세대수.1,세대당 인구.1,남자 인구수.1,여자 인구수.1,남여 비율.1
0,전국,"24,124,988","51,191,817","24,170,531",2.12,"25,484,498","25,707,319",0.99
1,서울특별시,"4,482,949","9,334,828","4,492,425",2.08,"4,505,412","4,829,416",0.93
2,부산광역시,"1,569,695","3,262,337","1,573,020",2.07,"1,587,357","1,674,980",0.95
3,대구광역시,"1,104,490","2,362,578","1,107,127",2.13,"1,158,607","1,203,971",0.96
4,인천광역시,"1,375,788","3,027,854","1,380,110",2.19,"1,512,651","1,515,203",1.00
5,광주광역시,"657,716","1,405,226","658,792",2.13,"693,552","711,674",0.97
6,대전광역시,"687,941","1,439,809","690,964",2.08,"717,573","722,236",0.99
7,울산광역시,"495,677","1,095,778","496,077",2.21,"563,999","531,779",1.06
8,세종특별자치시,"163,404","391,669","164,111",2.39,"194,967","196,702",0.99
9,경기도,"6,062,570","13,698,657","6,072,106",2.26,"6,883,368","6,815,289",1.01
10,강원특별자치도,"764,301","1,513,735","765,316",1.98,"761,064","752,671",1.01
11,충청북도,"787,774","1,590,107","789,271",2.01,"809,548","780,559",1.04
12,충청남도,"1,052,547","2,135,340","1,055,137",2.02,"1,095,862","1,039,478",1.05
13,전북특별자치도,"864,338","1,735,008","865,541",2.00,"864,313","870,695",0.99
14,전라남도,"912,344","1,785,487","913,114",1.96,"901,141","884,346",1.02
15,경상북도,"1,291,165","2,524,067","1,292,811",1.95,"1,277,157","1,246,910",1.02
16,경상남도,"1,537,606","3,221,132","1,539,748",2.09,"1,623,866","1,597,266",1.02
17,제주특별자치도,"314,683","668,205","314,861",2.12,"334,061","334,144",1.00