In [1]:
import pandas as pd
df = pd.read_excel('file/score.xlsx', index_col='지원번호')

In [5]:
df['키']>185

지원번호
1번     True
2번    False
3번    False
4번     True
5번     True
6번     True
7번     True
8번     True
Name: 키, dtype: bool

In [3]:
df = pd.read_excel('file/score.xlsx', index_col='지원번호')

### 문자열 함수 .str

In [9]:
# 문자열함수 str함수 - startswith:강으로 시작하는 문자열
# startswith,endswith,contains,lower,upper,capitalize
# replace - 대체
# split-분리,strip-공백제거,find-찾기,-1,len:글자수

# df[ df['이름'].str.startswith('강') ]
# df.loc[df['이름'].str.startswith('강')]

# contains 포함되어 있는 글자, ~ : not
# df[~df['이름'].str.contains('열')]

# lower,upper,capitalize
df['SW특기']
df['SW특기'].str.lower()
df['SW특기'].str.upper()
df['SW특기'].str.capitalize()

# isin : 여러개 검색 ['python','java']
langs = ['python','java']
# df[df['SW특기'].str.lower().isin(langs)] #SW특기 값 소문자로 변경후 리스트검색

# 
# df['SW특기'].str.lower().contains()
# df['SW특기']
# df['SW특기'].str.contains('Java',na=False)
# df[df['SW특기'].str.contains('Java',na=True)]  #na=True : NaN 데이터 출력
# df[df['SW특기'].str.contains('Java',na=False)]  #na=False : NaN 출력하지 않음
df[df['SW특기'].str.lower().str.contains('java',na=True)] # 소문자로 변경후 검색

# # unique 중복제거
# df['학교']
# df['학교'].unique()

       이름   학교    키  국어  영어  수학  과학  사회        SW특기
지원번호
2번    강태원  구로고  184  40  35  50  55  25        Java
3번    강호림  구로고  168  80  75  70  80  75  Javascript
4번    김수찬  구로고  187  40  60  70  75  80         NaN
5번    김재욱  구로고  188  15  20  10  35  10         NaN

In [ ]:
df = pd.read_excel('file/연령별인구현황_2025.xlsx',skiprows=3)
# 1개일때 str없이 사용, 여러개일때 str을 입력후 사용
# df[0,2] = df.iloc[0,2].replace(',','') # 천단위 표시 제거후 다시 저장
df['총 인구수'] = df['총 인구수'].str.replace(',','').astype(int)
df['총 인구수']

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Columns: 236 entries, 행정기관코드 to 100세 이상.17
dtypes: int64(2), str(234)
memory usage: 33.3 KB

c:\python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [57]:
df = pd.read_csv('file/drinks.csv')
df['continent'].unique()

<StringArray>
['AS', 'EU', 'AF', nan, 'SA', 'OC']
Length: 6, dtype: str

In [ ]:
df = pd.read_excel('file/students.xlsx',index_col='번호')
# s가 있는 이름을 모두 출력하시오. 대문자,소문자 모두 출력
# df[df['이름'].str.lower().str.contains('s')]
# df['학교'] = df['학교'].str.replace('등','승')
# df['학교'] = df['학교'] + '등학교'
# df['학교']

In [2]:
df = pd.read_excel('file/students.xlsx',index_col='번호')
# # SW특기 java,c
# langs = ['java','c']
# df[df['SW특기'].str.lower().isin(langs)]['SW특기']
# df.head(20)

# # java가 포함되어 있는 글자를 모두 출력하시오.
df[df['SW특기'].str.lower().str.contains('java',na=True)]

             이름    학교  학년    키  국어  영어  수학        SW특기
번호
13       Ardene  디지털고   2  161  91  97  33        JAVA
14      Sibylle   구로고   1  197  82  81  38        JAVA
17        Alric   구로고   1  193  68  96  76        JAVA
18        Mozes   신림고   1  176  61  44  51        JAVA
20       Emelia   신림고   1  199  85  27  31  Javascript
30       Urbain  디지털고   3  197  83  72  36  Javascript
32       Hamnet   신림고   3  171  95  55  65  Javascript
36      Ainslee  디지털고   2  201  66  15  89  Javascript
41         Lyle  디지털고   3  164  55  47  73  Javascript
46          Nat  디지털고   2  171  70  38  82  Javascript
54          Ula   신림고   3  168  80  59  85        java
55     Emmanuel   구로고   2  191  63  27  83        JAVA
56        Valle   신림고   3  167  68  83  52        java
60      Malynda  디지털고   1  178  57  79  72        java
65         Kiri   신림고   3  178  64  83  68        JAVA
66       Joanie   신림고   1  200  75  24  85        java
68        Tresa   구로고   2  166  58  37  70        java
73        Moise  디지털고   3  185  90  83  65        JAVA
74        Lewes  디지털고   2  187  61  22  43        JAVA
76       Dionis  디지털고   1  192  58  40  63  Javascript
79       Vannie  디지털고   1  184  95  27  64  Javascript
82       Jamill   구로고   2  182  98   8  60        java
84          Ola  디지털고   3  170  84  77  77  Javascript
89       Norris  디지털고   3  174  68   9  51        java
91       Marika   신림고   2  189  89  22  32  Javascript
94         Kaja   신림고   1  202  53  44  78        java
95   Clementine   신림고   1  194  71  13  81        JAVA
100    Jonathan  디지털고   2  195  84  63  80        JAVA