In [1]:
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False     # - 부호처리
matplotlib.rcParams['font.family'] = 'Malgun Gothic'  # 한글처리 : 윈도우 맑은고딕 저장
matplotlib.rcParams['font.size'] = 15                 # 전체 글자폰트크기 조정
# matplotlib.rcParams['font.family'] = 'AppleGothic'    # 맥컴 애플고딕 저장
import pandas as pd
import numpy as np

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
import requests
from bs4 import BeautifulSoup
import time
import os
from dotenv import load_dotenv

In [4]:
df = pd.read_csv('file/namu1.csv')
df.head(3)

   Unnamed: 0     title                                                url
0           0     조지 웨아  https://namu.wiki/w/%EC%A1%B0%EC%A7%80%20%EC%9...
1           1        경지             https://namu.wiki/w/%EA%B2%BD%EC%A7%80
2           2  군산 버스 19  https://namu.wiki/w/%EA%B5%B0%EC%82%B0%20%EB%B...

In [6]:
# df['url']

In [16]:
# for url in df['url'].head(50):
#     print(url)

In [ ]:
# url = 'https://namu.wiki/w/%EC%A1%B0%EC%A7%80%20%EC%9B%A8%EC%95%84'
# res = requests.get(url)
# soup = BeautifulSoup(res.text,'lxml') 
# title = soup.find('a',{'class':'J23-5aq4'}).get_text(strip=True) 
# category = soup.find('ul',{'class':'EVpyuXop'}).get_text(strip=True) 
# content = soup.find('div',{'class':'_6YZgjHNT Oud4u5fe'}).get_text(strip=True)

'라이베리아 공화국 대통령[ 펼치기 · 접기 ]초대제2대제3대제4대조셉 젠킨스 로버츠스티븐 앨런 벤슨대니얼 바시엘 워너제임스 스프릭스 페인제5대임시제6대제7대에드워드 제임스 로이최고임원위원회제임스 스키브링 스미스조셉 젠킨스 로버츠제8대제9대제10대제11대제임스 스프릭스 페인앤서니 W. 가디너앨프리드 프랜시스 러셀힐러리 R. W. 존슨제12대제13대제14대제15대조셉 제임스 치즈먼윌리엄 D. 콜먼개럿슨 W. 깁슨아서 바클레이제16대제17대제18대제19대대니얼 에드워드 히워드찰스 D. B. 킹에드윈 바클레이윌리엄 터브먼제20대제21대임시임시윌리엄 톨버트새뮤얼 케니언 도애이머스 소여데이비드 D. 크포르막포르임시임시제22대제23대윌턴 G. S. 산카울로루스 페리찰스 테일러모지스 블라임시제24대제25대제26대주드 브라이언트엘런 존슨 설리프조지 웨아조셉 보아카이라이베리아 부통령조지 웨아의 수상 이력[ 펼치기 · 접기 ]둘러보기 틀 모음개인 수상아프리카 올해의 축구 선수1989·1994·19951994-95 UCL 득점왕1995 발롱도르1995 FIFA 올해의 선수1995 옹즈도르베스트팀1995-96 ESM 올해의 팀1996 FIFA 올해의 선수수상호나우두2위조지 웨아3위앨런 시어러Player of the Year 1996수상호나우두2위앨런 시어러3위조지 웨아1996 Onze d\'OrOnze d\'OrOnze d\'ArgentOnze de Bronze에릭 칸토나조지 웨아마티아스 자머조지 웨아의 기타 정보[ 펼치기 · 접기 ]AC MILANHALL OF FAME[ 펼치기 · 접기 ]CHAMPIONS8에바니5코스타쿠르타13네스타21피를로5안퀼레티11모라4안첼로티11갈리6말디니32아비아티10세도르프11마사로32베컴10사비체비치4알베르티니1쿠디치니5갈리9인자기6바레시8가투소1게치1갈리7로데티4트라파토니9알타피니4칼라제5슈넬링거10후이 코스타8드사이2카푸23암브로시니12지다3말디니5데 베키22카카7도나도니10굴리트10보반GOLEADOR11질라르디노9보피7파투7세브첸코9인자기10리베라11산타고스티노11그렌9노르달9파팽9조던9알타피니10스키아피노99호나우두23시모네9반 바스텐9헤이틀리9콤빈20비어호프11프라티11비르디스8윌킨스22카카18바조80호나우지뉴11이브라히모비치BALLON D\'OR7세브첸코9웨아10리베라9파팽9반 바스텐22카카10굴리트CAPTAINS4비곤5벳9세베니니3말데라7스카리오니4보노미9소르마니5트레레4안노바치8로바티6말디니8사니8모란디3솔데라3자가티6바레시8레이카르트10리베라11모레티6안토니니9노르달9푸리첼리5킬핀1부폰9반 헤게11키아루지5페르베르시5로사토2살라23암브로시니2타소티10리드홀름8토뇬3말디니9부리니9안토넬리4베네티6부리아니9아르카리1로시27세르지뉴5바티스티니33실바11노벨리노IFFHS선정 남자축구 레전드[ 펼치기 · 접기 ]펠레디에고 마라도나로타어 마테우스페렌츠 푸스카스바이충 부티아알리 다에이디노 조프로베르토 바조나카타 히데토시차범근자셈 야쿱조지 웨아안토니오 카르바할라바 마제르우고 산체스요한 크루이프마르코 반 바스텐루드 굴리트윈턴 루퍼알프레도 디 스테파노호나우두라이언 긱스루카스 라데베랜던 도노반후안 알베르토 스키아피노스탠리 매튜스데이비드 베컴바비 찰튼올레흐 블로힌탄주 촐라크프란시스코 헨토마제드 압둘라레프 야신루이스 피구에우제비우호세 루이스 칠라베르트은완코 카누미셸 플라티니프란츠 베켄바워게르트 뮐러모하메드 아부트리카마흐무드 엘카팁지네딘 지단가린샤지쿠로저 밀러쑨지하이하오하이둥프랑코 바레시가브리엘 바티스투타데니스 베르캄프즈비그니에프 보니에크호베르투 카를루스페트르 체흐안드리 셰브첸코케니 달글리시에드가 다비즈알레산드로 델 피에로디디에 드록바사무엘 에투엔조 프란체스콜리게오르게 하지티에리 앙리올리버 칸카카케빈 키건마리오 켐페스미로슬라프 클로제로날드 쿠만필립 람미카엘 라우드루프유니스 마흐무드파올로 말디니라파엘 마르케스파벨 네드베드모하메드 누르제이제이 오코차아베디 펠레장마리 파프안드레아 피를로카를레스 푸욜라울 곤살레스프랑크 레이카르트히바우두호마리우호나우지뉴파올로 로시카를하인츠 루메니게페테르 슈마이켈흐리스토 스토이치코프다보르 슈케르프란체스코 토티카를로스 발데라마뤼트 판니스텔로이로빈 반 페르시사비 에르난데스라이베리아 공화국 제25대 대통령조지 웨아George Weah본명조지 타울론 마네 오퐁 오스만 웨아George Tawlon Manneh Oppong Ousman Weah출생1966년10월 1일(60세)라이베리아몬로비아국적라이베리아|프랑스[1]신체키185cm｜체중82kg[2]주발오른발직업축구 선수(스트라이커/은퇴)축구 감독은퇴정치인경력선수영 서바이버스 클래리턴 (1981~1984)봉레인지 컴퍼니 (1984~1985)마이티 바롤(1985~1986)인비서블 일레븐(1986~1987)아프리카 스포츠 내셔널 (1987)토네르 야운데 (1987~1988)AS 모나코 FC(1988~1992)파리 생제르맹 FC(1992~1995)AC 밀란(1995~2000)→첼시 FC(2000 /임대)맨체스터 시티 FC(2000)올랭피크 드 마르세유(2000~2001)알 자지라 클럽(2001~2003)감독라이베리아 대표팀(2001~2002 /선수 겸 감독)정치민주변화회의(2005~)라이베리아하원의원(몽세라도 주)제25대대통령2018년1월 22일~2024년1월 21일국가대표75경기[3]18골[4](라이베리아/ 1987~2018)링크|정보 더 보기[ 펼치기 · 접기 ]학력디브라이 대학교(경영학 / 석사[5])종교개신교(라이베리아 연합감리교회)[6]배우자클레어 웨아자녀조지 웨아 주니어,티모시 웨아등 슬하 4명[7]1. 개요2. 선수 경력2.1. 클럽 경력2.1.1.AS 모나코2.1.2.파리 생제르맹2.1.3.AC 밀란2.1.4.첼시 FC2.1.5.맨체스터 시티 FC2.1.6.올랭피크 드 마르세유2.1.7.알 자지라 클럽2.2. 국가대표2.3. 플레이 스타일3. 축구 선수로서의 평가4. 정치인 경력5. 기록5.1. 대회 기록5.2. 개인 수상6. 웨아에 대한 언사7. 여담1.개요[편집]라이베리아의축구 선수출신정치인.선수 시절에는AS 모나코,파리 생제르맹,AC 밀란등 유명 팀들을 두루 거치며아프리카인으로는 유일하게발롱도르와FIFA 올해의 선수를 수상한 인물이다.[8]2017년에 치러진 제 25대 라이베리아 대통령 선거에서대통령으로 당선되었으며, 2018년 1월 22일에 취임 했다. 2023년 재선에 도전 하였으나, 통일당 후보에게 밀려 낙선 했으며, 2024년 1월 21일 6년 임기를 마쳤다.2.선수 경력[편집]2.1.클럽 경력[편집]그의 부모님은 라이베리아의 소수 민족크루족으로 낙후 된 지역인 그랜드크루 주에서 수도 몬로비아로 이주해 빈민가인 클라라 타운에 정착하였다. 불우한 어린 시절을 보냈으며, 가족 관계에도 문제가 있어 웨아는 할머니 손에 자랐다.1981년 15세 때 3부 리그 소속 지역 축구 클럽인 영 서바이버스 클래리턴과 계약 하며골키퍼로 축구를 시작하였다. 하지만 골을 넣는 것에 대한 즐거움을 느끼게 되면서 공격수로 전향 했다.1984년 봉레인지 컴퍼니 유스팀으로 이적 하였다가, 1985년 마이티 배럴에서 프로 선수로 데뷔 하였다. 마이티 배럴에서 10경기에 출전해 7골을 기록 하며 활약 하였고, 1986년 라이베리아 최고의 팀이었던 인빈시블 일레븐으로 이 적하였다. 이 클럽에서주장을 맡고 23경기에 출전해 24골을 기록 하며리그 득점왕에 올랐다.이 활약으로 카메룬 스카우트의 눈에 띄어 1987년 코트디부아르 리그 소속의 아프리카 스포츠 내셔널로 이적 하였다가 카메룬 리그의 토네르 야운데로 이적 하였다. 토네르 야운데에서 18경기 15골을 기록 하며 활약을 이어갔다.2.1.1.AS 모나코[편집]아프리카에서는 이름을 알리기 시작 했지만,사실상 무명인 상태의 조지 웨아를 발탁 하여 국제 무대로 데려와서 성장시킨 인물은아르센 벵거였다. 벵거는 아프리카로 직접 가서 웨아의 모습을 수차례 지켜보았고, 1988년 벵거 감독이 이끄는AS 모나코 FC로 이적 했다.열악한 아프리카 리그에서 쥐꼬리만 한 연봉을 받으며 가족을 부양 했던 웨아는 당시 여러모로 열악한 상태였다. 사인을 하러 모나코에 왔을 때 당장 쓸 용돈이 한 푼도 없었기에, 벵거 감독이 용돈으로 500프랑을 줄 정도였다. 게다가 설상가상으로 팔이 골절 된 상태였다.구단에서도 의문을 표시 했으나,아르센 벵거는 웨아를 전적으로 신임 하며"열심히 하면 너는 최고의 선수가 될 수 있다"라고 격려 했다.그리고 진짜 그렇게 되었다.[9]웨아는 모나코에서 잠재력을 폭발시키며 1991년쿠프 드 프랑스에서 우승하였고, 이듬 해에는 팀을UEFA 컵위너스컵결승전으로 이끌었다. 모나코에서 4시즌 동안 102경기에 출장해 47골을 기록 했다.2.1.2.파리 생제르맹[편집]1992년파리 생제르맹으로 이적 했다. 이적한 뒤 첫 시즌인 92-93시즌에쿠프 드 프랑스에서 우승, 93-94시즌에는 리그 앙 우승을 거머쥐었다.94-95시즌은 조지 웨아의 선수 커리어 중 가장 영광스러운 시즌이었다.쿠프 드 프랑스와쿠프 드 라 리그에서 우승 하여도메스틱 컵 더블을 달성 했고, 7골을 넣으며UEFA 챔피언스 리그 득점왕을 달성 하면서바이에른과바르사를 꺾고 클럽 역사상 처음으로 챔피언스 리그 준결승 까지 진출 하는 데 기여 했다.웨아는 파리 생제르맹에서 3시즌 동안 96경기에 출장해 32골을 기록 했다.2.1.3.AC 밀란[편집]1995년 여름에AC 밀란으로 이적 했다. 지난 94-95시즌의 활약으로 발롱도르를 수상 받으며 첫 비 유럽인 발롱도르 수상자가 되었다.[10]또한 웨아는 밀란 시절  경이적인 신체 능력을 보여주며"블랙 다이아몬드"라고 불렀다.1996년 9월 8일 베로나 전에서 80m를 질주 하여 넣은 골은 그의 클래스를 보여준다. 이 골은현재 까지 영상 자료가 존재하는개인이 드리블로 돌파해 넣은 골 중 역대 최장거리 기록으로 알려져 있으며[11][12]지금 까지도치달의 상징이자축구 역사상 최고의 골 중 하나로 여겨진다.AC 밀란에서의 골AC 밀란에서 2회 리그 우승을 이끌며 5시즌 동안 114경기에 출장해 46골을 기록 했다.또한 1996년 5월대한민국 축구 국가대표팀과 친선 경기 목적으로AC 밀란소속으로 방한한 적이 있다. 결과는 2:3으로 한국의 역전승.#2.1.4.첼시 FC[편집]2000년첼시로 임대되어 11경기에 출장해 3골을 기록하며 팀의FA컵우승을 이끌었다.2.1.5.맨체스터 시티 FC[편집]이후 2000년 여름맨체스터 시티로 이적하여 7경기에 출장하였다.2.1.6.올랭피크 드 마르세유[편집]이후 \u200b\u200b올랭피크 드 마르세유로 이적해 19경기 5골을 기록하였다.2.1.7.알 자지라 클럽[편집]2001년 아랍에미리트의알 자지라 클럽으로 이적해 8경기 13골을 기록하였고, 2003년 선수 생활을 마감하였다.2.2.국가대표[편집]알프레도 디 스테파노[13],조지 베스트,라이언 긱스등과 더불어 선수로서의 명성에 대비되는 저조한 국대 커리어를 가진 선수로 자주 거론되는 선수로 허약한 그의 조국 대표팀을 이끌고 고군분투했으나, 팀의 한계를 극복하지 못한 채 국가대표 무대에서는 두각을 드러낼 기회조차 없었던 선수로 요약될 수 있다.라이베리아 축구 국가대표팀은월드컵은 물론아프리카 네이션스컵조차 예선 탈락이 다반사로 아프리카 내에서도 약체로 분류되는 선수단이었다.[14]1987년 1월 30일 서아프리카 네이션스컵 나이지리아 전에서 데뷔하였고, 그 경기에서 데뷔골도 기록하였다. 라이베리아 축구 국가대표팀은 정치권의 부정부패 때문에 충분한 지원을 받지 못해 웨아는 국가대항전 본선이 있을 때마다 사비를 털어야 했다. 라이베리아 팀의 주장으로 월드컵 본선 진출을 위해 도전했으나 꿈을 이루진 못하였다. 심지어 2002 한일 월드컵 때에는 35세의 노장이었던 그는 선수 겸 감독을 맡았지만 같은 조의 나이지리아에 승점 단 1점 차로 밀려 아깝게 본선 진출에 실패했다. 대신 2002년 아프리카 네이션스컵에서 본선에 진출했고 말리와의 경기에서 골을 기록하였다.[15]2018년, 라이베리아 현지시각 9월 11일에현직 대통령 신분으로 주장 완장을 차고 나이지리아와의 A매치 친선전에 나서며 뒤늦은 국가대표 은퇴 경기를 소화했다. 현역 시절 자신의 등번호였던 14번을 달고 뛰었는데, 라이베리아 축구 국가대표팀의 14번을 영구결번하기 위해서 만들어진 경기라고 한다. 조지 웨아는 79분간 경기를 뛰고 교체되었고, 라이베리아는 나이지리아에 아쉽게 2대1로 패하였다.2.3.플레이 스타일[편집]만능 완성형 포워드.폭발적인 주력을 낼 수 있으면서도 강인한 힘으로 상대 수비를 이겨낼 수 있는탄력적이면서도 강인한 신체 조건를 가졌다. 이 신체적 능력을 십분 활용 하며 상대 수비를 박살내고 골을 집어넣던 선수였다.거기에 더해진 좋은퍼스트 터치와 준수한드리블, 패스, 크로스 능력이 합쳐지고, 그 위에 더해진오프 더 볼능력이 웨아를 당대발롱도르 수상자로 만들었다.3.축구 선수로서의 평가[편집]명실상부 아프리카 역대 최고의 선수 중 한 명으로 평가 받는다.로저 밀러,디디에 드록바,사디오 마네,야야 투레,피에르에메릭 오바메양등 걸출한 아프리카인 축구 선수들이 있지만, 그들을 넘어사무엘 에투,모하메드 살라와 함께아프리카 역대 최고의 축구 선수로 평가 된다.4.정치인 경력[편집]정치인으로 활동 중인 모습내전으로 상처받은 조국 라이베리아를 위해 조지 웨아 기금을 설립하는 등 라이베리아 유니세프 친선 대사로 활동하였다. 이후 정치인으로 변신해2005년 라이베리아 대통령 선거에 일종의 제3지대격 포퓰리즘 빅텐트 우익 정당인 민주적 변화를 위한 회의(CDC) 후보로 출마하였다. 1차 투표에서는 275,265표(28.27%)로 후보 중 1위를 기록했지만 결투표 결과 327,046표(40.6%)를 획득하며 478,526표(59.4%)를 획득한 유엔 개발 프로그램의 아프리카 담당 재정국장으로 "철의 여인"이라고 불린 중도 자유주의 성향인 통일당(Unity Party) 소속의엘런 존슨 설리프(Ellen Johnson-Sirleaf)[16]에 151,480표 차이로 패하였다. 엘런 존슨-설리프(Ellen Johnson-Sirleaf) 는 2번 연임하며 12년 임기를 모두 채웠다.2017년 10월 10일 치러진 대선에 출마했는데, 1차 투표에서 39.0%를 받아 결선 투표에 진출했다. 결국 결선 투표에서 대통령으로 당선되었고,2018년1월 22일에 취임했다.#그런데 러닝메이트인 부통령 후보로 독재자찰스 테일러의 전 부인을 선택하고 옥중의 찰스 테일러와도 연락하여 논란이 되었으며, 심지어 선거에서도 찰스 테일러의 정당이었던 극우국가애국당과 연합을 해서 이겼다.#이게 보통 일이 아닌 것이 테일러는 그저 평범한 독재자가 아닌 아프리카 독재자들 중에서도 최악이라 평가받는 인물로, 라이베리아 내전의 주범이자 아프리카에서도 손꼽히는 대량학살자이며, 현재 재판에서 50년형을 선고받고 수감 중에 있다.[17]심지어 조지 웨아는 상기되어 있듯이 이 내전 당시평화운동가로 활동한 적이 있다.취임 후 1년이 넘은 2019년 5월 기준으로 달러 대비 라이베리아 달러 화폐 가치가 확 떨어지고 물가가 30% 가까이 상승[18]하여 경제적 불확실성에 시달리고 있다. 경제 성장률은 1.2%에서 0.4%로 추락하고, 먹고 살기 어려워진 시민 10,000여 명이인플레이션과 부패에 항의하여 거리시위를 하고 있다. 이에 조지 웨아 대통령은 현지시간 6월 6일에 연설에서 자신을 비난하는 시위자들에게 \'국가를 위협한다\'라며 용납하지 않겠다고 밝혔다.그 이후, 2023년 대선에서 결선 투표 끝에 낙선했다.#5.기록[편집]5.1.대회 기록[편집]마이티 배럴 (1985~1986)라이베리아 프리미어 리그: 1985-86라이베리아컵: 1985-86인비서블 일레븐 (1986~1987)라이베리아 프리미어 리그: 1986-87AS 모나코(1988~1992)쿠프 드 프랑스: 1991파리 생제르맹 FC(1992~1995)디비지옹 1: 1993-94쿠프 드 프랑스: 1992-93, 1994-95쿠프 드 라 리그: 1995AC 밀란(1995~2000)세리에 A: 1995-96, 1998-99첼시 FC(2000)FA컵: 1999-005.2.개인 수상[편집]발롱도르: 1995FIFA 올해의 선수: 1995아프리카 올해의 축구 선수: 1989, 1994, 1995디비지옹 1올해의 외국인 선수: 1990-91UEFA 챔피언스 리그득점왕: 1994-95BBC아프리카 올해의 축구 선수: 1995옹즈도르: 1995옹즈 드 옹즈: 1995, 1996ESM 올해의 팀: 1995-96FIFA XI: 1991, 1996 (리저브), 1997, 1998FIFA 페어플레이상: 1996엘 파이스 유럽 축구의 왕: 1995RSSSF 올해의 선수: 1995IFFHS세기의 아프리카 선수: 1996IFFHS 레전드: 2016IFFHS 올타임 아프리카 드림팀: 2016FIFA 100: 2004Arthur Ashe 용기상: 2004골든풋: 2005AC 밀란 명예의 전당: 2015발롱도르 드림팀후보: 2020 (CF 7위)6.웨아에 대한 언사[편집]조지 웨아는 놀라운 선수다. 나는 웨아 만큼 피치에서 폭발력을 지닌 선수를 본 적이 없다.-아르센 벵거조지 웨아는 내 선수 생활에 가장 큰 영향을 주었던 선수이자 나의 우상이다.-티에리 앙리[19]7.여담[편집]조지 웨아 본인과는 아무 상관이 없지만, 본인의 이름이 팔려 의문의 1패를 당한 황당한 과거가 있다.그레이엄 수네스문서 참조.집안의 거의 모든 구성원이 사실상 축구선수인데, 사촌인 크리스토퍼 웨아와 스티븐 웨아를 시작으로 장남인 조지 웨아 주니어[20], 미국 뉴욕에서 태어난 차남티모시 웨아[21], 친조카패트릭 웨아, 그리고 처조카카일 던컨이 축구선수이다.영어와프랑스어가 유창하다. 기본적으로 라이베리아 공용어가 영어고,리그 1에서 오래 뛰었기 때문이다.#조지 웨아 이전에도 축구선수 출신대통령이 있었다. 1954년부터 1955년까지 재임한카페 필류전브라질대통령이 최초의 축구선수 출신 대통령이고, 두 번째도 브라질 대통령을 지낸주앙 굴라르이며, 세 번째는튀르키예의에르도안이다. 조지 웨아 이후에는조지아에서미헤일 카벨라슈빌리가 내각제 개편 이후의 간선제이긴 하지만 대통령이 되었다.[22]물론 발롱도르까지 수상한 월드클래스 레벨의 프로 축구선수가 대통령까지 된 케이스는 아직까지 웨아가 유일하다.대통령 퇴임 후 2024년발롱도르시상식에 시상자로 등장해로드리에게 발롱도르를 수여했다.자신의 아들인 티모시 웨아와 함께 PSG와 마르세유에서 모두 선수로 뛴 기록을 가지고 있다.피파 시리즈와피파 온라인3에 World Legend 선수로 출시되어 큰 인기를 누렸다. 정계에 진출하면서[23]피파 18부터는 삭제되었다.[1]파리 생제르맹 FC에서 뛸 때 프랑스 시민권을 취득했다. 라이베리아 대선에 출마할 당시 이중국적 때문에 대선 출마가 좌절될 뻔했으나 라이베리아 법원에서 대선 출마에 문제가 없다고 판결을 내려 웨아는 라이베리아 대선에 출마·대통령에 취임할 수 있었다.[2]선수 시절[3]2018년에 51세의 나이로 자신의 마지막 A매치 경기를 치렀다.[4]라이베리아 축구 국가대표팀역대 최다 득점자[5]2013년 졸업[6]본래부터기독교가정에서 태어난 기독교인이었다가이슬람으로 개종한 후 다시 기독교로 개종했다.#UM News꽤나 논란이 있는나이지리아라고스의초교파은사주의대형 교회인Synagogue Church of All Nations(티비 조슈아설립)에서프린스 존슨과 함께 목격되기도 하였다.#[7]막내딸은 클레어 웨아에게서 태어나지 않은 이복자녀이며 2016년생이다[8]이후 아프리카 국적 선수의 포디움 수상은 조지 웨아 자신의 1996년 FIFA 올해의 선수 2위,사무엘 에투의 2005년 FIFA 올해의 선수 3위,모하메드 살라의 2018년과 2021년 FIFA 올해의 선수 3위,사디오 마네의 2022년 발롱도르 2위가 전부였다.디디에 드록바는 2007년 발롱도르 4위에 그쳤다.[9]웨아는 밀란에서발롱도르를 수상한 뒤 벵거에게 공을 돌렸다. 벵거는 자신이 발탁한 선수 중 가장 대단한 선수로 아직도 웨아를 꼽는다.[10]1994년까지 발롱도르는 유럽인으로 한정 해서 발롱도르를 뽑았으며, 이 때문에펠레나마라도나같은 축구의 신들 조차도 발롱도르를 수상 받지 못 했다.[11]기록으로만 남아 있는 역대 최장거리 골은펠레의 골이다. 무려자기 팀 골대 앞에서 부터 상대 팀 골대 바로 앞 까지 100m(!)를 혼자서 뚫어버리고 넣은 골로,이는 현재 라디오 중계 자료만 남아 있어 제대로 된 세계 기록으로는 인정 받지는 못 한다.[12]참고로 2번째로 긴 드리블 돌파 후 골의 주인공은 다름 아닌손흥민이다. 바로 그 유명한 2019-20 시즌 번리전의 75m 돌파 후 골.(웨아랑 고작 5m 차이만 난다) 이거 역시 영상이 남아 있다.[13]조지 웨아, 라이언 긱스 등과는 달리 국대를 하필 그 국대가 가장 약했던 시기만 골라 옮겨다녔기 때문이다. 스페인 축구팀과 아르헨티나 축구팀에서 뛴 바 있기 때문에 월드컵 커리어는 매우 부실하지만 소속 국가대표만은 매우 화려하다.[14]이는 셰브첸코나 긱스, 베일도 극복하지 못한 약체국의 필연이었다. 그나마 셰브첸코와 베일은 월드컵에 한번은 나갔다.[15]2무1패로 탈락하였다. 1경기 말리전, 2경기 알제리전 모두 1점차로 앞서다가 경기종료를 얼마 안 남겨두고 동점골을 내주었고, 나이지리아 전은 지면서 아쉽게 탈락하였다.[16]2011년노벨평화상수상.[17]이는 스포츠 선수가 정치에 얼마나 큰 영향을 끼칠 수 있는지 보여주는 사례이다. 독재자에 대한 반감마저 덮어버릴 정도로 영웅 취급을 받았다는 소리다. 물론 조지 웨아도 찰스 테일러 지지층이 아직 살아있으니 이걸 이용한 것이었다.[18]물가가 상승하기 직전에 1억 2,600 라이베리아 달러를 새로 찍어냈다고 한다.[19]조지 웨아의 AS 모나코 시절 부터 그의 팬이었다고 한다.[20]1987년생으로,AC 밀란유스 출신이며 2004년 미국 청소년 대표팀에 출장했으나 대성하지 못한 채 2018년 커리어를 마감했다.[21]성인 대표팀은 자신이 태어난 곳인미국을 선택했다.[22]카벨라슈빌리와 웨아는 둘 다 현역 시절맨체스터 시티 FC에서 뛰어봤다는 공통점이 있다. 다만 소속 시기가 달라 만난 적은 없다.[23]과거에도 World Legend에 합류한호마리우가 정계에 진출하면서 라이센스에서 삭제된 적이 있었다.'

In [19]:
data = []
for url in df['url'].head(50):
    # # 2. selenium : 자동화 도구 - 스크롤없이 가져옴
    # namu_url = url
    # options = Options()
    # options.add_experimental_option("excludeSwitches", ["enable-automation"])
    # options.add_experimental_option("useAutomationExtension", False)
    # options.add_argument("--disable-blink-features=AutomationControlled")
    # browser = webdriver.Chrome(options=options)
    # browser.maximize_window() # 화면 최대창 확대
    # browser.get(namu_url)
    # time.sleep(2)
    res = requests.get(url)
    time.sleep(1)
    soup = BeautifulSoup(res.text,'lxml') 
    title_tag = soup.find('a',{'class':'J23-5aq4'})
    title = title_tag.get_text(strip=True) if title_tag else None
    category_tag = soup.find('ul',{'class':'EVpyuXop'})
    category = category_tag.get_text(strip=True) if category_tag else None
    content_tag = soup.find('div',{'class':'_6YZgjHNT Oud4u5fe'})
    content = content_tag.get_text(strip=True) if content_tag else None
    data.append({
        'title':title,
        'category':category,
        'content':content
    })
    print(title)

print('완료')    


# # # 파일저장
# soup = BeautifulSoup(browser.page_source,'lxml')
# with open('file/namu_con1.html','w',encoding='utf-8') as f:
#     f.write(soup.prettify())

조지 웨아
경지
군산 버스 19
House 2
장갑기병 보톰즈 회색의 마녀
카드 앙 시엘/카드/드로
사용자:SamSara
제단(워크래프트 3)
빅 미키
제임스 로니
제25보병사단 DMZ 지뢰 폭발 사건
탱킹
와다
None
None
명탐정 코난: 시한장치의 마천루
제단(워크래프트 3)
영천시/정치
극장판 이나즈마 일레븐 최강군단 오우거의 습격
None
1991년 이라크 봉기
2003 쇼트트랙 스피드 스케이팅 유럽선수권 대회
불꽃 파이터즈/역대 전적/2026 시즌/경기 목록
흑색왜성
None
김환희/골 때리는 그녀들/클럽 경력
None
사용자:Hexy_Joe/빠른 이동 및 연습장
난칸마치
None
손무
FSO 폴로네즈
2002 쇼트트랙 스피드 스케이팅 유럽선수권 대회
PC정비사
불꽃 파이터즈/역대 전적/2026 시즌/경기 목록
분류:바트주의 이라크의 전쟁 및 전투
김환희/골 때리는 그녀들/클럽 경력/FC 액셔니스타
안양 정관장 레드부스터스
잔스파인/SD건담 지 제네레이션 이터널/UR
사용자:SamSara
부산 OK저축은행 읏맨
None
None
토오사카 린/작중 행적/본편
김주성(야구선수)/선수 경력
리그 오브 레전드/증강/프리즘
조지 웨아
사용자:Wpdl
아스파르
2025년/사건
완료

In [21]:
n_df = pd.DataFrame(data)
n_df.to_csv('file/namu2.csv')
n_df

,title,category,content
0,조지 웨아,1966년 출생1981년 데뷔2003년 은퇴2018년 은퇴라이베리아 대통령라이베리아...,라이베리아 공화국 대통령[ 펼치기 · 접기 ]초대제2대제3대제4대조셉 젠킨스 로버츠...
1,경지,경지나무위키 웹소설 프로젝트무공칭호(무협),경계선 지능의 줄임말에 대한 내용은경계선 지능문서를 참고하십시오.보드게임 '벚꽃 내...
2,군산 버스 19,군산시의 시내버스,군산시시내버스 노선[ 펼치기 · 접기 ]미성동010203070809옥구읍111213...
3,House 2,2026년 Windows 게임미국 게임액션 어드벤처 게임호러 게임,하우스 2House 2개발Bark Bark Games유통Glowstick Enter...
4,장갑기병 보톰즈 회색의 마녀,보톰즈 시리즈일본 애니메이션/목록2026년 애니메이션 영화2026년 4분기 일본 애...,로도스도 전기에 등장하는 '회색의 마녀'에 대한 내용은칼라(포세리아)문서를 참고하십...
5,카드 앙 시엘/카드/드로,인티 크리에이츠카드 앙 시엘카드 앙 시엘/카드,카드 앙 시엘 카드 목록0코스트3코스트드로디버그리부트무브메모리 리크변신브레이크 포인...
6,사용자:SamSara,NaN,NaN
7,제단(워크래프트 3),워크래프트 3/건물,1. 개요2. 시스템3. 종류4. 여담Altar1.개요[편집]워크래프트 3의 종족 ...
8,빅 미키,토마스와 친구들/등장인물TUGS/등장인물1989년 창조된 캐릭터,크레인들[ 펼치기 · 접기 ]노스 웨스턴 철도 소속크랭키칼리빅 미키레지테스협궤 철도...
9,제임스 로니,1984년 출생2006년 데뷔2019년 은퇴미국의 야구 선수휴스턴 출신 인물외국인 ...,제임스 로니 관련 틀[ 펼치기 · 접기 ]로스앤젤레스 다저스역대 1라운드 지명선수[...
10,제25보병사단 DMZ 지뢰 폭발 사건,이재명 정부/사건사고/2026년대한민국 육군/사건 사고지뢰제25보병사단김정은 시대연...,한시적 넘겨주기로 연결되는 다른 문서에 대한 내용은 아래 문서를 참고하십시오.9월 ...
11,탱킹,스포츠 용어,MMORPG에서의 탱킹에 대한 내용은탱커문서를 참고하십시오.1. 개요2. 의도 및 ...
12,와다,성씨/일본,1. 개요2. 실존 인물3. 가상 인물1.개요[편집]わだ2015년 기준 和田는 42...
13,NaN,NaN,NaN
14,NaN,NaN,NaN
15,명탐정 코난: 시한장치의 마천루,명탐정 코난(애니메이션)/극장판일본 애니메이션/목록1997년 애니메이션 영화1997...,극장판[ 펼치기 · 접기 ]1기2기3기4기5기시한장치의 마천루(줄거리/쿠키 영상)1...
16,제단(워크래프트 3),워크래프트 3/건물,1. 개요2. 시스템3. 종류4. 여담Altar1.개요[편집]워크래프트 3의 종족 ...
17,영천시/정치,영천시경상북도의 정치,상위 문서:영천시관련 문서:영천시·청도군경상북도정치[ 펼치기 · 접기 ]경산시경주시...
18,극장판 이나즈마 일레븐 최강군단 오우거의 습격,이나즈마 일레븐 시리즈/애니메이션일본 애니메이션/목록2010년 애니메이션 영화일본의...,[ 펼치기 · 접기 ]무인 시리즈(애니메이션)이나즈마 일레븐이나즈마 일레븐 RE이나...
19,NaN,NaN,NaN
20,1991년 이라크 봉기,아시아의 봉기1991년 정치바트주의 이라크의 전쟁 및 전투사담 후세인이란-이라크 관...,1991년 이라크 봉기1991 Iraqi uprisings반군에 의해 파괴된 이라크...
21,2003 쇼트트랙 스피드 스케이팅 유럽선수권 대회,쇼트트랙 스피드 스케이팅 유럽선수권 대회,←2001-02ISU 쇼트트랙 스피드 스케이팅 2002-03 시즌2003-04→[ ...
22,불꽃 파이터즈/역대 전적/2026 시즌/경기 목록,불꽃야구2026년 야구2026년 방송 프로그램,상위 문서:불꽃 파이터즈/역대 전적/2026 시즌1. 개요1.1. 시즌 포맷 변경점...
23,흑색왜성,왜성(천체)가설상의 천체,편집 보호된 문서입니다. 문서의ACL 탭을 확인하세요.항성의진화[ 펼치기 · 접기 ...
24,NaN,NaN,NaN
25,김환희/골 때리는 그녀들/클럽 경력,FC 액셔니스타/현역,상위 문서:김환희/골 때리는 그녀들1. 개요2. 클럽2.1.FC 액셔니스타1.개요[...
26,NaN,NaN,NaN
27,사용자:Hexy_Joe/빠른 이동 및 연습장,NaN,NaN
28,난칸마치,구마모토현의 정1957년 설치된 행정구역,구마모토현시정촌[ 펼치기 · 접기 ]정령지정도시현청정령구마모토시(▶ 하위 행정구역)...
29,NaN,NaN,NaN
30,손무,몰년 미상춘추전국시대 및 진나라(영성)의 철학자둥잉시 출신 인물군사학자,손자(인물)은(는) 여기로 연결됩니다. 제(齊)나라의 손자(孫子)에 대한 내용은손빈...
31,FSO 폴로네즈,FSO/생산차량1978년 출시된 자동차2002년 단종된 자동차중형 해치백중형 왜건그룹 4,Polonez[1]1. 개요2. 배경 및 개발3. 출시 및 생산3.1. 폴로네즈(1...
32,2002 쇼트트랙 스피드 스케이팅 유럽선수권 대회,쇼트트랙 스피드 스케이팅 유럽선수권 대회,←2000-01ISU 쇼트트랙 스피드 스케이팅 2001-02 시즌2002-03→[ ...
33,PC정비사,컴퓨터정보통신자격면허,(사)한국정보평가협회(KIE)가 운영하는 국가공인민간자격증에 대한 내용은PC Mas...
34,불꽃 파이터즈/역대 전적/2026 시즌/경기 목록,불꽃야구2026년 야구2026년 방송 프로그램,상위 문서:불꽃 파이터즈/역대 전적/2026 시즌1. 개요1.1. 시즌 포맷 변경점...
35,분류:바트주의 이라크의 전쟁 및 전투,바트주의 이라크이라크의 전쟁 및 전투,
36,김환희/골 때리는 그녀들/클럽 경력/FC 액셔니스타,FC 액셔니스타/현역,상위 문서:김환희/골 때리는 그녀들/클럽 경력김환희시즌 8-소속 팀FC 액셔니스타소...
37,안양 정관장 레드부스터스,안양 정관장 레드부스터스한국인삼공사안양시 연고 구단대한민국의 프로 농구단한국프로농구...,2026-27 시즌에 대한 내용은안양 정관장 레드부스터스/2026-27 시즌문서를 ...
38,잔스파인/SD건담 지 제네레이션 이터널/UR,SD건담 지 제네레이션 이터널/유닛G제네레이션 시리즈/오리지널 기체베스파의 모빌슈트,"다른 지 제네레이션 시리즈에서의 잔스파인에 대한 내용은잔스파인문서를, 원작의 파라 ..."
39,사용자:SamSara,NaN,NaN
40,부산 OK저축은행 읏맨,부산 OK저축은행 읏맨OK금융그룹부산광역시 연고 구단연고지 이전대한민국의 프로 배구...,2026-27 시즌에 대한 내용은부산 OK저축은행 읏맨/2026-27 시즌문서를 참...
41,NaN,NaN,NaN
42,NaN,NaN,NaN
43,토오사카 린/작중 행적/본편,Fate 시리즈/캐릭터/작중 행적토오사카 린,상위 문서:토오사카 린/작중 행적이 문서에스포일러가 포함되어 있습니다.이 문서가 설...
44,김주성(야구선수)/선수 경력,대한민국의 야구 선수/경력,상위 문서:김주성(야구선수)1. 개요2. 아마추어 시절3.LG 트윈스3.1. 201...
45,리그 오브 레전드/증강/프리즘,리그 오브 레전드/증강,상위 문서:리그 오브 레전드/증강리그 오브 레전드의증강실버골드프리즘1. 개요2. 공...
46,조지 웨아,1966년 출생1981년 데뷔2003년 은퇴2018년 은퇴라이베리아 대통령라이베리아...,라이베리아 공화국 대통령[ 펼치기 · 접기 ]초대제2대제3대제4대조셉 젠킨스 로버츠...
47,사용자:Wpdl,NaN,NaN
48,아스파르,고트족동음이의어동로마 제국의 군인동로마의 섭정400년 출생471년 사망고대 로마의 ...,프린세스 메이커 5의 인물에 대한 내용은아스파르(프린세스 메이커 5)문서를 참고하십...
49,2025년/사건,2025년/사건사고,상위 문서:2025년연도별 사건 문서 바로가기2025년 사건←2024년 사건2026...